export const projects = [
  {
    id: "01",
    title: "Digital Expiry Tracker",
    subtitle: "Intelligent Inventory Management",
    philosophy: "Computer vision and OCR pipelines that automate expiry monitoring — replacing error-prone manual processes with intelligent, real-time label recognition.",
    tags: ["Computer Vision", "OCR", "Python", "FastAPI"],
    status: "ACTIVE",
    metric: { value: "95%", label: "Detection Accuracy" },
    accentColor: { primary: "rgba(0,212,240,0.10)", line: "rgba(0,212,240,0.45)", text: "#00D4F0" },
    rationale: {
      challenge: "Manual expiry monitoring in retail and household environments is error-prone, time-consuming, and scales poorly across thousands of SKUs.",
      approach: "Dual OCR pipeline with adaptive image preprocessing, intelligent date extraction, and contextual label parsing for real-world label recognition across varied packaging formats.",
      impact: "Automated expiry tracking system with smart reminders, real-time inventory monitoring, and AI-assisted scanning — reducing human error by orders of magnitude.",
    },
  },
  {
    id: "02",
    title: "Navjeevan AI",
    subtitle: "Agricultural Intelligence Platform",
    philosophy: "Conversational AI that bridges the information gap for rural farmers — delivering localized, actionable agricultural guidance through natural language.",
    tags: ["LLMs", "NLP", "FastAPI", "Intent Classification"],
    status: "ACTIVE",
    metric: { value: "10K+", label: "Farmers Reached" },
    accentColor: { primary: "rgba(232,168,124,0.08)", line: "rgba(232,168,124,0.35)", text: "#E8A87C" },
    rationale: {
      challenge: "Farmers in rural regions lack easy access to contextual agricultural guidance, government scheme information, and timely crop advisories.",
      approach: "LLM-powered intent classification pipeline with structured retrieval, contextual response generation, and multi-lingual support for regional accessibility.",
      impact: "AI farming assistant delivering localized, actionable agricultural guidance through conversational interaction — democratizing expert knowledge.",
    },
  },
  {
    id: "03",
    title: "AI Stock Analysis Dashboard",
    subtitle: "Explainable Financial Intelligence",
    philosophy: "Interpretable AI-assisted forecasting that doesn't just predict — it explains why. Making machine intelligence transparent for financial decision-making.",
    tags: ["LSTM", "TensorFlow", "Time-Series", "Explainable AI"],
    status: "ARCHIVED",
    metric: { value: "3×", label: "Faster Analysis" },
    accentColor: { primary: "rgba(180,100,255,0.08)", line: "rgba(180,100,255,0.30)", text: "#B464FF" },
    rationale: {
      challenge: "Most stock prediction systems operate as black boxes — lacking interpretability and meaningful decision support for human analysts.",
      approach: "Combined LSTM forecasting with technical indicator analysis and explainable signal reasoning, surfacing the 'why' behind every prediction.",
      impact: "Interactive financial intelligence dashboard with AI-assisted trend analysis, contextual recommendations, and transparent decision rationale.",
    },
  },
];
